### ISSUE TITLE
If a player is using the chainsaw and a teammate backs into them it will crash the server.

### ISSUE THREAD

**Issue by GonzoHow** [0125/sourcemod-ff#26]
Reproduced this issue with the latest version of Sourcemod stable.

**Comment by GonzoHow** [comment]
Hello 0125, just tested on a server with the latest stable versions of Sourcemod and Metamod the bug still exists even after recompile.  You don't even have to back into someone; just try to chainsaw them.

**Comment by 0125** [comment]
Hey man, Thanks for the heads up. Thought this would work, I'll look into it properly.  will just not reverse ff chainsaw DMG if I can't find the issue

**Comment by GonzoHow** [comment]
After a lot of unnecessary chainsawing, can confirm this resolved the issue!
